apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    app: authentication-service
    component: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: management
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: authentication-service
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service-headless
  labels:
    app: authentication-service
    component: backend
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: authentication-service